"use strict";

/**
 * engineering-backlog.js — CODEGA AI Mühendislik Backlog Motoru
 *
 * Sprint XX: Autonomous Evolution Platform (AEP)
 *
 * Sistemdeki her zayıflık bir Engineering Task olur.
 * Her task: ID, severity, category, effort, impact, risk, modules, agent.
 * Backlog her zaman canlıdır — yeni bulgular otomatik eklenir.
 */

const fs   = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");

// ── Sabitler ─────────────────────────────────────────────────────────────────

const SEVERITY = Object.freeze({
  CRITICAL : "critical",   // Uygulama açılmıyor / veri kaybı
  HIGH     : "high",       // Önemli özellik bozuk
  MEDIUM   : "medium",     // Performans / kullanılabilirlik sorunu
  LOW      : "low",        // Küçük iyileştirme
  INFO     : "info",       // Bilgi / gözlem
});

const CATEGORY = Object.freeze({
  BUG            : "bug",
  PERFORMANCE    : "performance",
  TECH_DEBT      : "tech_debt",
  SECURITY       : "security",
  TEST_COVERAGE  : "test_coverage",
  DOCUMENTATION  : "documentation",
  ARCHITECTURE   : "architecture",
  DUPLICATE_CODE : "duplicate_code",
  MEMORY_LEAK    : "memory_leak",
  MISSING_FEATURE: "missing_feature",
  BUILD_FAILURE  : "build_failure",
  REGRESSION     : "regression",
  PLUGIN_HEALTH  : "plugin_health",
  REASONING      : "reasoning",
});

const TASK_STATUS = Object.freeze({
  OPEN        : "open",
  IN_PROGRESS : "in_progress",
  PATCH_READY : "patch_ready",
  PR_OPEN     : "pr_open",
  RESOLVED    : "resolved",
  WONT_FIX    : "wont_fix",
});

const EFFORT = Object.freeze({ XS: "xs", S: "s", M: "m", L: "l", XL: "xl" });

// ── Factory ──────────────────────────────────────────────────────────────────

function createTask({
  title,
  description   = "",
  severity      = SEVERITY.MEDIUM,
  category      = CATEGORY.TECH_DEBT,
  effort        = EFFORT.M,
  impact        = 5,       // 1–10
  riskScore     = 3,       // 1–10
  modules       = [],      // etkilenen modüller
  agent         = "builder",
  sourceAnalysis = null,   // hangi analiz buldu
  autoGenerated = false,
} = {}) {
  if (!title) throw new Error("EngineeringTask: title zorunlu");
  return {
    id          : "ET-" + crypto.randomBytes(4).toString("hex").toUpperCase(),
    title       : String(title).trim(),
    description : String(description).trim(),
    severity,
    category,
    effort,
    impact      : Math.min(10, Math.max(1, Number(impact) || 5)),
    riskScore   : Math.min(10, Math.max(1, Number(riskScore) || 3)),
    modules     : Array.isArray(modules) ? modules : [],
    agent,
    sourceAnalysis,
    autoGenerated: Boolean(autoGenerated),
    status      : TASK_STATUS.OPEN,
    priority    : 0,   // hesaplanır
    prUrl       : null,
    branchName  : null,
    patchResult : null,
    createdAt   : Date.now(),
    updatedAt   : Date.now(),
    resolvedAt  : null,
    notes       : [],
  };
}

// ── Öncelik Hesaplama ─────────────────────────────────────────────────────────

const SEVERITY_WEIGHT = {
  [SEVERITY.CRITICAL]: 50,
  [SEVERITY.HIGH]    : 30,
  [SEVERITY.MEDIUM]  : 15,
  [SEVERITY.LOW]     : 5,
  [SEVERITY.INFO]    : 1,
};

const EFFORT_COST = { xs: 1, s: 2, m: 3, l: 5, xl: 8 };

/**
 * Öncelik skoru = (severity_weight + impact * 2) / effort_cost
 * Yüksek skor = önce yapılmalı
 */
function calcPriority(task) {
  const sw = SEVERITY_WEIGHT[task.severity] || 10;
  const cost = EFFORT_COST[task.effort] || 3;
  return Math.round(((sw + task.impact * 2) / cost) * 10) / 10;
}

// ── EngineeringBacklog Sınıfı ─────────────────────────────────────────────────

class EngineeringBacklog {
  constructor(dataDir) {
    this._dataDir  = dataDir;
    this._filePath = path.join(dataDir, "engineering-backlog.json");
    this._tasks    = new Map(); // id → task
  }

  /** Disk'ten yükle */
  init() {
    try {
      fs.mkdirSync(this._dataDir, { recursive: true });
      if (fs.existsSync(this._filePath)) {
        const raw = JSON.parse(fs.readFileSync(this._filePath, "utf8"));
        for (const t of (raw.tasks || [])) {
          t.priority = calcPriority(t);
          this._tasks.set(t.id, t);
        }
      }
    } catch (e) {
      console.warn("[EngineeringBacklog] init:", e.message);
    }
    return this;
  }

  /** Disk'e kaydet */
  _save() {
    try {
      fs.writeFileSync(this._filePath, JSON.stringify({
        version: 1,
        savedAt : Date.now(),
        tasks   : [...this._tasks.values()],
      }, null, 2), "utf8");
    } catch (e) {
      console.warn("[EngineeringBacklog] save:", e.message);
    }
  }

  /**
   * Yeni task ekle (duplikat title kontrolü ile).
   * @param {object} opts  — createTask parametreleri
   * @returns {object}     — oluşturulan task
   */
  add(opts) {
    // Aynı başlıkta açık task varsa ekle
    const dup = [...this._tasks.values()].find(
      t => t.title === String(opts.title || "").trim() &&
           t.status === TASK_STATUS.OPEN
    );
    if (dup) return dup;

    const task = createTask(opts);
    task.priority = calcPriority(task);
    this._tasks.set(task.id, task);
    this._save();
    return task;
  }

  /** Bulk add — analiz sonucundan gelen zayıflık listesi */
  addFromAnalysis(weaknesses = []) {
    const added = [];
    for (const w of weaknesses) {
      try { added.push(this.add({ ...w, autoGenerated: true })); } catch (_) {}
    }
    return added;
  }

  /** Belirli bir task'ı güncelle */
  update(id, patch = {}) {
    const task = this._tasks.get(id);
    if (!task) throw new Error(`Task bulunamadı: ${id}`);
    Object.assign(task, patch, { updatedAt: Date.now() });
    if (patch.status === TASK_STATUS.RESOLVED) task.resolvedAt = Date.now();
    task.priority = calcPriority(task);
    this._save();
    return task;
  }

  /** Not ekle */
  addNote(id, note) {
    const task = this._tasks.get(id);
    if (!task) throw new Error(`Task bulunamadı: ${id}`);
    task.notes.push({ text: String(note), at: Date.now() });
    task.updatedAt = Date.now();
    this._save();
    return task;
  }

  /** Tek task getir */
  get(id) { return this._tasks.get(id) || null; }

  /**
   * Task listesi — filtreli + öncelik sıralı
   * @param {{ status?, severity?, category?, limit? }} opts
   */
  list({ status = null, severity = null, category = null, limit = 100 } = {}) {
    let tasks = [...this._tasks.values()];
    if (status)   tasks = tasks.filter(t => t.status === status);
    if (severity) tasks = tasks.filter(t => t.severity === severity);
    if (category) tasks = tasks.filter(t => t.category === category);
    tasks.sort((a, b) => b.priority - a.priority);
    return tasks.slice(0, limit);
  }

  /** Açık task'lar */
  openTasks() { return this.list({ status: TASK_STATUS.OPEN }); }

  /** Kritik açık task'lar */
  criticalTasks() { return this.list({ status: TASK_STATUS.OPEN, severity: SEVERITY.CRITICAL }); }

  /** Özet istatistik */
  summary() {
    const all = [...this._tasks.values()];
    const byStatus   = {};
    const bySeverity = {};
    const byCategory = {};
    for (const t of all) {
      byStatus[t.status]     = (byStatus[t.status]     || 0) + 1;
      bySeverity[t.severity] = (bySeverity[t.severity] || 0) + 1;
      byCategory[t.category] = (byCategory[t.category] || 0) + 1;
    }
    const open = all.filter(t => t.status === TASK_STATUS.OPEN);
    return {
      total     : all.length,
      open      : open.length,
      critical  : open.filter(t => t.severity === SEVERITY.CRITICAL).length,
      highPriority: open.filter(t => t.priority >= 20).length,
      byStatus,
      bySeverity,
      byCategory,
      topTasks  : open.slice(0, 5).map(t => ({ id: t.id, title: t.title, priority: t.priority, severity: t.severity })),
    };
  }

  count() { return this._tasks.size; }
}

// ── Singleton ─────────────────────────────────────────────────────────────────

let _instance = null;

function getBacklog(dataDir) {
  if (!_instance) {
    _instance = new EngineeringBacklog(dataDir);
    _instance.init();
  }
  return _instance;
}

module.exports = {
  EngineeringBacklog,
  createTask,
  calcPriority,
  getBacklog,
  SEVERITY,
  CATEGORY,
  TASK_STATUS,
  EFFORT,
};
