"use strict";

/**
 * improvement-planner.js — CODEGA AI İyileştirme Planlayıcı
 *
 * Sprint XX: Autonomous Evolution Platform (AEP)
 *
 * Zayıflık → Teknik Öneri dönüşümü.
 * Her öneri: etki tahmini, maliyet tahmini, regresyon riski, uygulama sırası.
 * Önce yüksek etki / düşük risk / düşük maliyet kombinasyonları öne çıkar.
 */

const fs   = require("node:fs");
const path = require("node:path");
const { SEVERITY, CATEGORY, EFFORT } = require("./engineering-backlog");

// ── Öneri Türleri ─────────────────────────────────────────────────────────────

const PROPOSAL_TYPE = Object.freeze({
  REFACTOR      : "refactor",
  BUG_FIX       : "bug_fix",
  TEST_ADDITION : "test_addition",
  PERF_OPT      : "perf_optimization",
  SECURITY_PATCH: "security_patch",
  DOC_UPDATE    : "doc_update",
  ARCH_REDESIGN : "arch_redesign",
  DEPENDENCY_UPD: "dependency_update",
  FEATURE_ADD   : "feature_addition",
});

const PROPOSAL_STATUS = Object.freeze({
  DRAFT     : "draft",
  APPROVED  : "approved",
  REJECTED  : "rejected",
  IN_PATCH  : "in_patch",
  COMPLETED : "completed",
});

// ── Öneri Fabrikası ───────────────────────────────────────────────────────────

function createProposal({
  taskId,
  title,
  type          = PROPOSAL_TYPE.REFACTOR,
  description   = "",
  implementation = "",    // Ne yapılacak
  expectedImpact = "",    // Etki açıklaması
  impactScore    = 5,     // 1–10
  effortEstimate = EFFORT.M,
  regressionRisk = 3,     // 1–10
  implementationOrder = 1,
  affectedFiles  = [],
  suggestedAgent = "builder",
  autoGenerated  = false,
} = {}) {
  if (!taskId) throw new Error("Proposal: taskId zorunlu");
  if (!title)  throw new Error("Proposal: title zorunlu");

  const roi = calcROI(impactScore, effortEstimate, regressionRisk);

  return {
    id       : "PR-" + Date.now().toString(36).toUpperCase(),
    taskId,
    title    : String(title).trim(),
    type,
    description  : String(description).trim(),
    implementation: String(implementation).trim(),
    expectedImpact: String(expectedImpact).trim(),
    impactScore  : Math.min(10, Math.max(1, Number(impactScore) || 5)),
    effortEstimate,
    regressionRisk: Math.min(10, Math.max(1, Number(regressionRisk) || 3)),
    implementationOrder,
    affectedFiles: Array.isArray(affectedFiles) ? affectedFiles : [],
    suggestedAgent,
    autoGenerated: Boolean(autoGenerated),
    roi,
    status   : PROPOSAL_STATUS.DRAFT,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    approvedAt: null,
    completedAt: null,
    rejectionReason: null,
  };
}

// ROI = (impact * 10) / (effort_cost * regression_penalty)
const EFFORT_COST = { xs: 1, s: 2, m: 3, l: 5, xl: 8 };
function calcROI(impact, effort, regressionRisk) {
  const cost = (EFFORT_COST[effort] || 3) * (1 + regressionRisk * 0.1);
  return Math.round((impact * 10) / cost * 10) / 10;
}

// ── Kural Tabanlı Öneri Üretici ──────────────────────────────────────────────

/**
 * Backlog task'ından otomatik öneri üret.
 * LLM gerektirmez — heuristic kural seti.
 * @param {object} task  — EngineeringTask
 * @returns {object[]}   — öneri dizisi (genellikle 1, bazen 2)
 */
function generateProposalsForTask(task) {
  const proposals = [];

  const base = {
    taskId       : task.id,
    autoGenerated: true,
    affectedFiles: task.modules.map(m => `src/main/agent/${m}`),
    suggestedAgent: task.agent,
  };

  switch (task.category) {
    case CATEGORY.BUG:
      proposals.push(createProposal({
        ...base,
        title          : `Fix: ${task.title}`,
        type           : PROPOSAL_TYPE.BUG_FIX,
        description    : task.description,
        implementation : "Kök nedeni tespit et, minimal kod değişikliği ile düzelt, regresyon testi yaz.",
        expectedImpact : "Hata ortadan kalkar, kullanıcı deneyimi iyileşir.",
        impactScore    : task.severity === SEVERITY.CRITICAL ? 10 : task.severity === SEVERITY.HIGH ? 7 : 5,
        effortEstimate : task.effort,
        regressionRisk : 4,
      }));
      break;

    case CATEGORY.PERFORMANCE:
      proposals.push(createProposal({
        ...base,
        title          : `Perf: ${task.title}`,
        type           : PROPOSAL_TYPE.PERF_OPT,
        description    : task.description,
        implementation : "Profil al, darboğazı bul, algoritma veya önbellek optimizasyonu uygula.",
        expectedImpact : "Yanıt süresi azalır, kaynak kullanımı düşer.",
        impactScore    : task.impact,
        effortEstimate : task.effort,
        regressionRisk : 3,
        suggestedAgent : "performance",
      }));
      break;

    case CATEGORY.TECH_DEBT:
      proposals.push(createProposal({
        ...base,
        title          : `Refactor: ${task.title}`,
        type           : PROPOSAL_TYPE.REFACTOR,
        description    : task.description,
        implementation : "Kod yeniden yapılandır, büyük fonksiyonları böl, tekrarlı kodu ortak modüle taşı.",
        expectedImpact : "Okunabilirlik artar, bakım kolaylaşır, gelecek sprint'ler hızlanır.",
        impactScore    : task.impact,
        effortEstimate : task.effort,
        regressionRisk : 5,
      }));
      break;

    case CATEGORY.TEST_COVERAGE:
      proposals.push(createProposal({
        ...base,
        title          : `Tests: ${task.title}`,
        type           : PROPOSAL_TYPE.TEST_ADDITION,
        description    : task.description,
        implementation : "Eksik birim testleri yaz, edge case'leri kapsа, CI coverage eşiğini güncelle.",
        expectedImpact : "Regresyon riski düşer, refactor güveni artar.",
        impactScore    : 6,
        effortEstimate : EFFORT.S,
        regressionRisk : 1,
        suggestedAgent : "qa",
      }));
      break;

    case CATEGORY.SECURITY:
      proposals.push(createProposal({
        ...base,
        title          : `Security: ${task.title}`,
        type           : PROPOSAL_TYPE.SECURITY_PATCH,
        description    : task.description,
        implementation : "Güvenlik açığını kapat, input validasyonu ekle, output encoding uygula.",
        expectedImpact : "Güvenlik skoru artar, saldırı yüzeyi daralır.",
        impactScore    : 9,
        effortEstimate : task.effort,
        regressionRisk : 4,
        suggestedAgent : "security",
      }));
      break;

    case CATEGORY.ARCHITECTURE:
      proposals.push(createProposal({
        ...base,
        title          : `Arch: ${task.title}`,
        type           : PROPOSAL_TYPE.ARCH_REDESIGN,
        description    : task.description,
        implementation : "Yeni modül sınırları çiz, sorumlulukları ayır, arayüzleri sözleşme olarak tanımla.",
        expectedImpact : "Mimari skor artar, bağımlılık karmaşıklığı azalır.",
        impactScore    : 8,
        effortEstimate : EFFORT.L,
        regressionRisk : 7,
        suggestedAgent : "architect",
      }));
      break;

    case CATEGORY.DOCUMENTATION:
      proposals.push(createProposal({
        ...base,
        title          : `Docs: ${task.title}`,
        type           : PROPOSAL_TYPE.DOC_UPDATE,
        description    : task.description,
        implementation : "JSDoc ekle, CHANGELOG güncelle, README örneklerini tazele.",
        expectedImpact : "Yeni geliştirici oryantasyonu hızlanır.",
        impactScore    : 3,
        effortEstimate : EFFORT.XS,
        regressionRisk : 1,
        suggestedAgent : "documentation",
      }));
      break;

    default:
      proposals.push(createProposal({
        ...base,
        title          : `Improve: ${task.title}`,
        type           : PROPOSAL_TYPE.REFACTOR,
        description    : task.description,
        implementation : "İlgili modülleri incele, kapsamlı iyileştirme planı oluştur.",
        expectedImpact : "Genel kod kalitesi artar.",
        impactScore    : task.impact,
        effortEstimate : task.effort,
        regressionRisk : 3,
      }));
  }

  return proposals;
}

// ── ImprovementPlanner Sınıfı ─────────────────────────────────────────────────

class ImprovementPlanner {
  constructor(dataDir) {
    this._dataDir  = dataDir;
    this._filePath = path.join(dataDir, "improvement-proposals.json");
    this._proposals = new Map();
  }

  init() {
    try {
      fs.mkdirSync(this._dataDir, { recursive: true });
      if (fs.existsSync(this._filePath)) {
        const raw = JSON.parse(fs.readFileSync(this._filePath, "utf8"));
        for (const p of (raw.proposals || [])) this._proposals.set(p.id, p);
      }
    } catch (e) {
      console.warn("[ImprovementPlanner] init:", e.message);
    }
    return this;
  }

  _save() {
    try {
      fs.writeFileSync(this._filePath, JSON.stringify({
        version  : 1,
        savedAt  : Date.now(),
        proposals: [...this._proposals.values()],
      }, null, 2), "utf8");
    } catch (e) {
      console.warn("[ImprovementPlanner] save:", e.message);
    }
  }

  /** Backlog task'larından otomatik öneri üret */
  planForTasks(tasks = []) {
    const newProposals = [];
    for (const task of tasks) {
      const existing = [...this._proposals.values()].filter(p => p.taskId === task.id);
      if (existing.length) continue; // zaten planlanmış
      const generated = generateProposalsForTask(task);
      for (const p of generated) {
        this._proposals.set(p.id, p);
        newProposals.push(p);
      }
    }
    if (newProposals.length) this._save();
    return newProposals;
  }

  /** Manuel öneri ekle */
  add(opts) {
    const p = createProposal(opts);
    this._proposals.set(p.id, p);
    this._save();
    return p;
  }

  /** Öneri güncelle */
  update(id, patch = {}) {
    const p = this._proposals.get(id);
    if (!p) throw new Error(`Öneri bulunamadı: ${id}`);
    Object.assign(p, patch, { updatedAt: Date.now() });
    this._save();
    return p;
  }

  approve(id)         { return this.update(id, { status: PROPOSAL_STATUS.APPROVED, approvedAt: Date.now() }); }
  reject(id, reason)  { return this.update(id, { status: PROPOSAL_STATUS.REJECTED, rejectionReason: reason }); }
  complete(id)        { return this.update(id, { status: PROPOSAL_STATUS.COMPLETED, completedAt: Date.now() }); }

  get(id) { return this._proposals.get(id) || null; }

  /**
   * Onaylanmayı bekleyen, ROI sıralamalı öneri listesi
   */
  listPrioritized({ status = null, limit = 50 } = {}) {
    let proposals = [...this._proposals.values()];
    if (status) proposals = proposals.filter(p => p.status === status);
    proposals.sort((a, b) => b.roi - a.roi);
    return proposals.slice(0, limit);
  }

  drafts()    { return this.listPrioritized({ status: PROPOSAL_STATUS.DRAFT }); }
  approved()  { return this.listPrioritized({ status: PROPOSAL_STATUS.APPROVED }); }

  summary() {
    const all = [...this._proposals.values()];
    const byStatus = {};
    for (const p of all) byStatus[p.status] = (byStatus[p.status] || 0) + 1;
    const topROI = [...all].sort((a, b) => b.roi - a.roi).slice(0, 3)
      .map(p => ({ id: p.id, title: p.title, roi: p.roi, status: p.status }));
    return { total: all.length, byStatus, topROI };
  }
}

module.exports = {
  ImprovementPlanner,
  createProposal,
  generateProposalsForTask,
  calcROI,
  PROPOSAL_TYPE,
  PROPOSAL_STATUS,
};
